### ISSUE TITLE
Finish up testing in v1.4

### ISSUE THREAD

**Issue by jq1836** [AY2223S1-CS2103T-W12-3/tp#179]
# Tests to be added to the following classes:
## Logic
- [x] `BookCommand` (Alvin)
- [x] `UnbookCommand` (Alvin)
- [x] `VenueAddCommand` (Alvin)
- [x] `VenueDeleteCommand` (Alvin)
- [ ] `VenueViewCommand` (Naren)

## Model
- [X] VenueBook (Nicholas)
- [X] UniqueVenueList (Nicholas)
- [x] Venue (Nicholas) 
- [x] DailySchedule (Nicholas)
- [ ] BookingDescriptor (Naren)
- [ ] RecurrentBooking (Naren)
- [x] ModelManager (Neale)

## Storage
- [x] `JsonAdaptedRecurrentBooking` (Neale)
- [x] `JsonAdaptedVenue` (Neale)
- [x] `JsonSerializableVenueBook` (Neale)
- [x] `JsonVenueBookStorage` (Neale)
- [x] `DataStorageManager` (Neale)
- [x] `StorageManager` (Neale)

**Comment by alvinjiang1** [comment]
Testing for v1.4 has completed. Remaining Testing not planned
