### ISSUE TITLE
Customize application to contain RC4 related information

### ISSUE THREAD

**Issue by alvinjiang1** [AY2223S1-CS2103T-W12-3/tp#2]
As a user, I can view relevant information about RC4 residents

**Comment by jq1836** [comment]
As discussed, include:
1. `n/NAME`
2. ` p/PHONE_NUMBER`
3. `e/EMAIL`
4. `r/FLOOR-UNIT`
5. `g/GENDER`
6. `h/HOUSE`
7. `m/MATRIC_NUMBER`
8. `t/TAG`
