### ISSUE TITLE
[PE-D][Tester C] Invalid example (given in add resident) inside user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-3/tp#204]
![Screenshot 2022-10-28 at 4.17.22 PM.png](https://raw.githubusercontent.com/benjytan45678/ped/main/files/a9c5eb8e-cc17-4cb7-9c14-3a5cc3f9eb43.png)

The above resident will not be added into RC4HDB, due to invalid phone number. (since it only contains 7 numbers)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: benjytan45678/ped#1

**Comment by alvinjiang1** [comment]
Closed as of #302
