### ISSUE TITLE
[PE-D][Tester D] Error message for room number does not correspond with expected outcome.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-3/tp#221]
![image.png](https://raw.githubusercontent.com/janelleljt/ped/main/files/fc8a50b4-cf14-4043-a9e8-5f9226708450.png)
When adding a room number XX-00, an error message specifying that the room number should be non-negative is shown. However, 00 is not negative and hence, should be an acceptable input.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: janelleljt/ped#3

**Comment by nareus** [comment]
Change UG and error message for room format to positive
