### ISSUE TITLE
Implement back-to-top for UGDG

### ISSUE THREAD

**Issue by nealetham** [AY2223S1-CS2103T-W12-3/tp#46]
As mentioned in the 2101 tutorial lessons, one of the main methods of increasing navigability in our user guides and developer guide is to add a back-to-top button in our guides.

We can possibly add it after each section, or each subsection, or even at the bottom of the document.

**Comment by jq1836** [comment]
Issue moved to Project board [here](https://github.com/orgs/AY2223S1-CS2103T-W12-3/projects/1/views/1).
