### ISSUE TITLE
Update documentation and testing for FilterCommand

### ISSUE THREAD

**Issue by alvinjiang1** [AY2223S1-CS2103T-W12-3/tp#63]
Follow up to issue #6 and PR #59.  

## To do for Testing:
- [x] `FilterCommandParser`
- [x] `FilterCommand`
- [x] `AttributesMatchKeywordsPredicate`

Click [here](https://app.codecov.io/gh/jq1836/tp/commit/587df69120d91e1aafb6b3a885725e869599eb16) for code coverage details such as which lines to focus on.
Green - Covered
Yellow - Partially covered
Red - Not covered

## To do for Documentation:
- [ ] Update UG/DG.
- [ ] Make minor Javadocs edits as pointed out in PR #59.

**Comment by jq1836** [comment]
Let's discuss during our meeting how we can upgrade the `FilterCommand`. Therefore, let's wait till then before updating the UG/DG. The Javadocs edits can proceed.
