### ISSUE TITLE
Modify delete command (from AB3) to allow for multiple objects to be deleted at once

### ISSUE THREAD

**Issue by nseah21** [AY2223S1-CS2103T-W12-3/tp#8]
As a user, I can delete multiple residents' data from the app quickly so that I can save time.

**Comment by jq1836** [comment]
Implement through delete command chaining

**Comment by jq1836** [comment]
User story moved to Project user stories board [here](https://github.com/orgs/AY2223S1-CS2103T-W12-3/projects/1/views/5).
