### ISSUE TITLE
Post-v1.2 UGDG updates 

### ISSUE THREAD

**Issue by nealetham** [AY2223S1-CS2103T-W12-3/tp#88]
Because we were rushing for the deadline, I think a lot of us missed the updating of relevant portions in the UGDG. Listed below are some of the portions. 

Add/Remove, Check them if necessary:

## UG:
- To discuss how we can restructure the UG (etc. maintain single page linearity or create new pages for each section)

### Logic Component
- [ ] Update diagram and text to reflect the refactoring of `Commands` into `MiscCommands`, `ModelCommands`, `StorageCommands` and `StorageModelCommands`.

### UI Component
- [x] Update diagram and text to reflect the removal of `PersonListPanel` and `PersonCard`, and the addition of `ResidentTableView`

### Model Component & Storage Component 
- [ ] Update diagram and text to reflect the refactoring of `Person` to `Resident`

### User Stories
- [ ] Update the relevant portions of User Stories to reflect any new functionalities or extensions that the user story might have

**Comment by jq1836** [comment]
Refer to [this](https://jq1836.github.io/tp/) page for an idea of how multi-page implementation looks like.
